#!/bin/bash

function short_help {
  printf "Usage: ./manage collect|install|help\n"
}

function full_help {
  printf "Config repository helper script.\n\nUsage:\n\t./manage collect|install|help\n\nEnvironment:\n\tDESTDIR\tsystem root\n\tHOME\tuser home dir, relative to root\n"
}

function collect {
  cp -vL $DESTDIR$HOME/.bashrc home

  cp -vLr $DESTDIR$HOME/.config/{i3,sway} config
}

# todo rewrite this as loops for simplicity and modifiability
function _install {
  install -m 744 home/.bashrc $DESTDIR$HOME/ -v

  mkdir -pv .config/{i3,sway,sway/config.d}
  install -m 644 config/i3/* $DESTDIR$HOME/.config/i3 -v
  install -m 644 config/sway/* $DESTDIR$HOME/.config/sway -v
  install -m 644 config/sway/config.d/* $DESTDIR$HOME/.config/sway/config.d -v
}

if [ "$#" -eq 0 ]; then
  help
  exit 0
fi

case "$1" in
  "collect") 
    collect;;
  "install") 
    _install;;
  "help") 
    full_help;;
  *)
    short_help;;
esac
